from flask import render_template

from astro import app
from astro.scrape import main

@app.route('/')
@app.route('/index')
def index():

    # scraped_data = main()
    # print(scraped_data)
    scraped_data = ({'picture-of-the-day': ('http://www.astronomy.com/-/media/Images/Photo of Day/Large Images/2019/03/APOD20190329.jpg?mw=600', 'Deep view of the Pleiades'), 'news': [('http://www.astronomy.com/observing/sky-this-week/2019/03/the-sky-this-week-from-march-29-to-april-7', 'The Sky This Week from March 29 to April 7'), ('http://www.astronomy.com/news/2019/03/the-case-for-trident-nasas-shrinking-window-for-a-mission-to-triton', 'The case for Trident: NASA’s shrinking window for a mission to Triton'), ('http://www.astronomy.com/news/2019/03/ligo-is-searching-for-gravitational-waves-again', "LIGO is searching for gravitational waves again, and here's what scientists hope to learn")]}, {'picture-of-the-day': ('https://apod.nasa.gov/image/1903/MarkarianChain_Kaminsky_960.jpg', " Markarian's Chain of Galaxies "), 'news': []}, {'picture-of-the-day': ('https://cdn.mos.cms.futurecdn.net/TpgrtYe4yXqt2sybLvQA7h-600-80.jpg', 'https://www.space.com/triton-mission-concepts-to-neptune-moon.html'), 'news': [('https://www.space.com/39251-on-this-day-in-space.html', 'On This Day in Space! March 31, 1962: NASA Approves Gemini Spacecraft Design'), ('https://www.space.com/israel-moon-lander-nasa-instrument.html', "NASA's Piggyback Experiment on Israeli Moon Lander Could Aid Future Lunar Touchdowns"), ('https://www.space.com/triton-mission-concepts-to-neptune-moon.html', "Next Stop, Triton? Here's Two Wild Ideas to Explore Neptune's Weirdest Moon"), ('https://www.space.com/amazing-spacewalk-photos-space-station-expedition-59.html', 'The Spacewalks of Expedition 59 in Photos'), ('https://www.space.com/smithsonian-debuts-apollo-11-new-exhibit.html', "Smithsonian Debuts Apollo 11 '50 Years from Tranquility Base' Exhibit")]}, {'picture-of-the-day': (), 'news': [('https://www.skyandtelescope.com/astronomy-news/saturn-cassini-rings-moons/', 'Saturn’s Rings Built Up Its Tiny, Close-in Moons'), ('https://www.skyandtelescope.com/astronomy-news/best-view-yet-baby-giant-exoplanet/', 'Best View Yet of Baby Giant Exoplanet'), ('https://www.skyandtelescope.com/astronomy-news/quaking-aspen-potential-power-source-mars/', 'Quaking Aspen Leaves Inspire Potential Power Source For Mars Rovers'), ('https://www.skyandtelescope.com/astronomy-news/100-days-next-total-solar-eclipse/', 'It’s Less Than 100 Days Until the Next Total Solar Eclipse'), ('https://www.skyandtelescope.com/astronomy-news/hayabusa-2-asteroid-ryugu-young-dark-dry/', 'Hayabusa 2 Finds Asteroid Ryugu Is Young, Dark & Dry')]})
    return render_template('index.html', data=scraped_data)
